# Generated by Django 5.2.5 on 2025-09-03 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sagile_id', models.CharField(help_text='Unique SAgile project identifier', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on-hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current project status', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('current_sprint', models.CharField(blank=True, help_text="Current sprint (e.g., 'Sprint 3 (Week 2)')", max_length=50)),
                ('has_repository', models.BooleanField(default=False, help_text='Whether this project has a linked repository')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('scrum-master', 'Scrum Master'), ('developer', 'Developer'), ('project-manager', 'Project Manager'), ('tester', 'Tester'), ('product-owner', 'Product Owner')], help_text="User's role in this specific project", max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Membership',
                'verbose_name_plural': 'Project Memberships',
                'db_table': 'project_memberships',
            },
        ),
    ]
