# Generated by Django 5.2.5 on 2025-09-03 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Repository name (lowercase, alphanumeric, hyphens only)', max_length=100, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Repository name can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('description', models.TextField(blank=True, help_text='Repository description')),
                ('access_level', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('internal', 'Internal')], default='private', help_text='Repository access level', max_length=10)),
                ('project_type', models.CharField(choices=[('fresh', 'Fresh Project'), ('upload', 'Upload Existing Files'), ('template', 'From Template')], default='fresh', help_text='How the project was initialized', max_length=10)),
                ('root_path', models.CharField(blank=True, help_text='Root path of the repository in the file system', max_length=500)),
                ('is_initialized', models.BooleanField(default=False, help_text='Whether the repository has been initialized with files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Relative path of the file in the repository', max_length=500)),
                ('file_name', models.CharField(help_text='Name of the file', max_length=255)),
                ('file_type', models.CharField(choices=[('code', 'Code File'), ('config', 'Configuration'), ('documentation', 'Documentation'), ('test', 'Test File'), ('asset', 'Asset'), ('other', 'Other')], default='code', help_text='Type of file', max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last time the file was modified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repository File',
                'verbose_name_plural': 'Repository Files',
                'db_table': 'repository_files',
                'ordering': ['file_path'],
            },
        ),
    ]
