# Generated by Django 5.2.5 on 2025-09-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('repositories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this repository', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='project',
            field=models.OneToOneField(help_text='Linked SAgile project', on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='projects.project'),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repositoryfile',
            name='repository',
            field=models.ForeignKey(help_text='Repository this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='repositories.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='repositoryfile',
            unique_together={('repository', 'file_path')},
        ),
    ]
