# Generated by Django 5.2.5 on 2025-09-03 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the file containing the code', max_length=500)),
                ('file_name', models.CharField(help_text='Name of the file', max_length=255)),
                ('selected_text', models.TextField(help_text='The actual code text that was selected')),
                ('start_line', models.PositiveIntegerField(help_text='Starting line number of the selection')),
                ('end_line', models.PositiveIntegerField(help_text='Ending line number of the selection')),
                ('start_column', models.PositiveIntegerField(blank=True, help_text='Starting column position', null=True)),
                ('end_column', models.PositiveIntegerField(blank=True, help_text='Ending column position', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Code Link',
                'verbose_name_plural': 'Code Links',
                'db_table': 'code_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Unique task identifier (e.g., PROJ-123)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(help_text='Detailed task description')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress'), ('code-review', 'Code Review'), ('testing', 'Testing'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', help_text='Current task status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Task priority level', max_length=10)),
                ('progress', models.IntegerField(default=0, help_text='Task completion percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete', max_digits=5, null=True)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours spent', max_digits=5)),
                ('due_date', models.DateTimeField(blank=True, help_text='Task due date', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task was started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('is_progress_update', models.BooleanField(default=False, help_text='Whether this is a progress update comment')),
                ('old_progress', models.IntegerField(blank=True, help_text='Previous progress value (for progress updates)', null=True)),
                ('new_progress', models.IntegerField(blank=True, help_text='New progress value (for progress updates)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Task Comment',
                'verbose_name_plural': 'Task Comments',
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
